import pygame
import time
import RPi.GPIO as GPIO
import random

GPIO.setmode(GPIO.BCM)

GPIO.setup(5, GPIO.OUT) #L5
GPIO.setup(6, GPIO.OUT) #L4
GPIO.setup(13, GPIO.OUT) #L3
GPIO.setup(19, GPIO.OUT) #L2
GPIO.setup(26, GPIO.OUT) #L1

GPIO.setup(16, GPIO.OUT) #M1
GPIO.setup(20, GPIO.OUT) #M2
GPIO.setup(21, GPIO.OUT) #M3

GPIO.setup(2, GPIO.OUT) #d1
GPIO.setup(3, GPIO.OUT) #d2
GPIO.setup(4, GPIO.OUT) #d3
GPIO.setup(17, GPIO.OUT) #d4
GPIO.setup(27, GPIO.OUT) #d5
GPIO.setup(22, GPIO.OUT) #d6
GPIO.setup(10, GPIO.OUT) #d7
GPIO.setup(9, GPIO.OUT) #d8
GPIO.setup(11, GPIO.OUT) #d9
GPIO.setup(18, GPIO.OUT) #d10
GPIO.setup(23, GPIO.OUT) #d11
GPIO.setup(24, GPIO.OUT) #d12
GPIO.setup(25, GPIO.OUT) #d13
GPIO.setup(8, GPIO.OUT) #d14
GPIO.setup(7, GPIO.OUT) #d15
GPIO.setup(12, GPIO.OUT) #d16



def red_pwm():
    pwm=GPIO.PWM(5, 5000)
    pwm.start(100)
    a=100

    while a>0:
        pwm.ChangeDutyCycle(a)
        a=a-1
        time.sleep(0.05)

    
    pwm.stop()
    

def bottom_pwm():
    pwm=GPIO.PWM(26, 5000)
    pwm.start(100)
    a=100

    while a>0:
        pwm.ChangeDutyCycle(a)
        a=a-1
        time.sleep(0.05)

    
    pwm.stop()

    
def fpoint():
    GPIO.output(5, True)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    GPIO.output(2, GPIO.LOW)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.LOW)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.LOW)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)
    
def randled():
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)
    alledgeoff()
    alloff()
    time.sleep(0.05)
    
    i = random.choice([5,6,13,19,26])
    GPIO.output(i, True)
    j = random.choice([2,3,4,17,27,22,10,9,11,18,23,24,25,8,7,12])
    GPIO.output(j, GPIO.LOW)
    time.sleep(0.05)
    
    
    
def test():
    for i in range(1, 65):
        randled()


def edgemove():  
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    
    GPIO.output(2, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(2, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(3, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(3, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(4, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(4, GPIO.HIGH)
    
    time.sleep(0.05)
    GPIO.output(17, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(17, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(27, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(27, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(22, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(22, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(10, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(10, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(9, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(9, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(11, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(11, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(18, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(18, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(23, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(23, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(24, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(24, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(25, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(25, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(8, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(8, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(7, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(7, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(12, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)

def edgemove2():
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    time.sleep(0.05)
    
    GPIO.output(2, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(2, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(3, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(3, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(4, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(4, GPIO.HIGH)
    
    time.sleep(0.05)
    GPIO.output(17, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(17, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(27, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(27, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(22, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(22, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(10, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(10, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(9, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(9, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(11, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(11, GPIO.HIGH)
    time.sleep(0.05)
    GPIO.output(18, GPIO.LOW)
    time.sleep(0.05)
    GPIO.output(18, GPIO.HIGH)
    time.sleep(0.05)

def alledgeoff():
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)


def alledgeon():
    GPIO.output(2, GPIO.LOW)
    GPIO.output(3, GPIO.LOW)
    GPIO.output(4, GPIO.LOW)
    GPIO.output(17, GPIO.LOW)
    GPIO.output(27, GPIO.LOW)
    GPIO.output(22, GPIO.LOW)
    GPIO.output(10, GPIO.LOW)
    GPIO.output(9, GPIO.LOW)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(18, GPIO.LOW)
    GPIO.output(23, GPIO.LOW)
    GPIO.output(24, GPIO.LOW)
    GPIO.output(25, GPIO.LOW)
    GPIO.output(8, GPIO.LOW)
    GPIO.output(7, GPIO.LOW)
    GPIO.output(12, GPIO.LOW)
    
    
def oddnumber():
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)  
    GPIO.output(2, GPIO.LOW)
    GPIO.output(4, GPIO.LOW)
    GPIO.output(27, GPIO.LOW)
    GPIO.output(10, GPIO.LOW)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(23, GPIO.LOW)
    GPIO.output(25, GPIO.LOW)
    GPIO.output(7, GPIO.LOW)

def evennumber():
    GPIO.output(3, GPIO.LOW)
    GPIO.output(17, GPIO.LOW)
    GPIO.output(22, GPIO.LOW)
    GPIO.output(9, GPIO.LOW)
    GPIO.output(18, GPIO.LOW)
    GPIO.output(24, GPIO.LOW)
    GPIO.output(8, GPIO.LOW)
    GPIO.output(12, GPIO.LOW)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    
    
def allon():
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    
    
def alloff():
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)


def alloff2():
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)
    
    
def midmove():
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.05)
    
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.05)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.05)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, True)
    time.sleep(0.05)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.05)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, True)
    time.sleep(0.05)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.05)
    
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.05)
    
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.05)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.05)
    
def side1():
    GPIO.output(2, GPIO.LOW)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.LOW)
    GPIO.output(8, GPIO.LOW)
    GPIO.output(7, GPIO.LOW)
    GPIO.output(12, GPIO.LOW)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)
    
def side2():
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(3, GPIO.LOW)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.LOW)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)
    
def side3():
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.LOW)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.LOW)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.HIGH)
    
def side4():
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.LOW)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.LOW)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.LOW)
    
def side5():
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.LOW)
    GPIO.output(22, GPIO.LOW)
    GPIO.output(10, GPIO.LOW)
    GPIO.output(9, GPIO.LOW)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)


def side24():
    GPIO.output(2, GPIO.HIGH)
    GPIO.output(3, GPIO.LOW)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.LOW)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.LOW)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.LOW)
    GPIO.output(25, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.LOW)

def side15():
    GPIO.output(2, GPIO.LOW)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.LOW)
    GPIO.output(22, GPIO.LOW)
    GPIO.output(10, GPIO.LOW)
    GPIO.output(9, GPIO.LOW)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.LOW)
    GPIO.output(8, GPIO.LOW)
    GPIO.output(7, GPIO.LOW)
    GPIO.output(12, GPIO.LOW)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)
    
def side135():
    GPIO.output(2, GPIO.LOW)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.LOW)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.LOW)
    GPIO.output(22, GPIO.LOW)
    GPIO.output(10, GPIO.LOW)
    GPIO.output(9, GPIO.LOW)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.LOW)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.LOW)
    GPIO.output(8, GPIO.LOW)
    GPIO.output(7, GPIO.LOW)
    GPIO.output(12, GPIO.LOW)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.HIGH)
    

def cross():
    side135()
    GPIO.output(5, True)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.05)
    
    side24()
    GPIO.output(5, True)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.05)
        
    side135()
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, False)
    time.sleep(0.05)
    
    side24()
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, False)
    time.sleep(0.05)
    
    
    
def wave():
    side1()
    ## line 1
    time.sleep(0.1)
    
    side2()
    ## line 2
    time.sleep(0.1)
    
    side3()
    ## line 3
    time.sleep(0.1)
    
    side4()
    ## line 4
    time.sleep(0.1)
    
    side5()
    ## line 5
    time.sleep(0.1)
    
    
def fastup():
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.2)
    
    
def fastdown():
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.2)
    
def fastheart():
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side3()
    time.sleep(0.01)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    side24()
    time.sleep(0.01)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    side15()
    time.sleep(0.01)
    
def slowheart():
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side3()
    time.sleep(0.02)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    side24()
    time.sleep(0.02)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    side15()
    time.sleep(0.02)
    
    
def square():
    alledgeoff()
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW)
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    
def center():
    alledgeoff()
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.HIGH)
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    
    

def manyfastheart():
    a = 0
    while(a<40):
        fastheart()
        a=a+1
    
    
def manyslowheart():
    a = 0
    while(a<40):
        slowheart()
        a=a+1
    
    
def birthday():
    pygame.init()
    pygame.mixer.music.load("Happy.mp3")
    pygame.mixer.music.play()


    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(1)
    
    alledgeoff()
    
    GPIO.output(26, True) 
    GPIO.output(19, True)
    time.sleep(1)
    
    alledgeoff()

    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW)
    time.sleep(1)
    
    alledgeon()
    
    ##all off
    time.sleep(1.5)

    GPIO.output(3, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)

    
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    time.sleep(0.2)
    GPIO.output(13, True)
    time.sleep(0.2)
    GPIO.output(6, True)
    time.sleep(0.2)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    
    
    evennumber()
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
   
    oddnumber()
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
    
    evennumber()
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
    
    oddnumber()
    GPIO.output(5, True)
    time.sleep(0.5)
    
    edgemove()
    edgemove()
    
    alloff()
    time.sleep(0.05)
    
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    time.sleep(0.5)
    GPIO.output(19, False)
    time.sleep(0.5)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    time.sleep(0.5)
    GPIO.output(13, False)
    time.sleep(0.5)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    time.sleep(0.5)
    GPIO.output(6, False)
    time.sleep(0.5)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.5)
    GPIO.output(5, False)
    time.sleep(0.5)
    
    alloff()
    time.sleep(0.05)
    GPIO.output(5, True)
    time.sleep(0.5)
    GPIO.output(6, True)
    time.sleep(0.5)
    GPIO.output(13, True)
    time.sleep(0.5)
    GPIO.output(19, True)
    time.sleep(0.5)
    GPIO.output(26, True)
    time.sleep(0.5)
    
    alloff()
    time.sleep(0.05)
    
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    time.sleep(0.5)
    GPIO.output(19, False)
    time.sleep(0.5)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    time.sleep(0.5)
    GPIO.output(13, False)
    time.sleep(0.5)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    time.sleep(0.5)
    GPIO.output(6, False)
    time.sleep(0.5)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.5)
    GPIO.output(5, False)
    time.sleep(0.5)
    
    alloff()
    time.sleep(0.05)
    GPIO.output(5, True)
    time.sleep(0.5)
    GPIO.output(6, True)
    time.sleep(0.5)
    GPIO.output(13, True)
    time.sleep(0.5)
    GPIO.output(19, True)
    time.sleep(0.5)
    GPIO.output(26, True)
    time.sleep(0.5)
    
    ##slow mid move
    midmove()
    midmove()
    midmove()
    
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
    wave()
   
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(0.5)
    GPIO.output(5, True)
    time.sleep(1.5)
    GPIO.output(5, False)
    time.sleep(0.5)
    
    
    GPIO.output(2, GPIO.LOW)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.HIGH)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.HIGH)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.LOW)
    GPIO.output(8, GPIO.LOW)
    GPIO.output(7, GPIO.LOW)
    GPIO.output(12, GPIO.LOW)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)
    
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(5, False)
    time.sleep(0.5)
    GPIO.output(5, True)
    time.sleep(1.5)
    
    
    alledgeon()
    allon()
    time.sleep(1)
    alloff()
    time.sleep(1)
    allon()
    time.sleep(1)
    alloff()
    time.sleep(1)
    allon()
    time.sleep(1)
    alloff()
    time.sleep(1)
    allon()
    time.sleep(1)
    
    midmove()
    midmove()
    midmove()
    
    oddnumber()
    midmove()
    midmove()
    midmove()
    midmove()
    
    evennumber()
    midmove()
    midmove()
    midmove()
    midmove()
    
    
    oddnumber()
    midmove()
    midmove()
    midmove()
    midmove()
    
    evennumber()
    midmove()
    midmove()
    midmove()
    midmove()
    
    edgemove()

    GPIO.output(2, GPIO.LOW)
    GPIO.output(3, GPIO.HIGH)
    GPIO.output(4, GPIO.HIGH)
    GPIO.output(17, GPIO.HIGH)
    GPIO.output(27, GPIO.LOW)
    GPIO.output(22, GPIO.HIGH)
    GPIO.output(10, GPIO.HIGH)
    GPIO.output(9, GPIO.HIGH)
    GPIO.output(11, GPIO.LOW)
    GPIO.output(18, GPIO.HIGH)
    GPIO.output(23, GPIO.HIGH)
    GPIO.output(24, GPIO.HIGH)
    GPIO.output(25, GPIO.LOW)
    GPIO.output(8, GPIO.HIGH)
    GPIO.output(7, GPIO.HIGH)
    GPIO.output(12, GPIO.HIGH)
    GPIO.output(16, GPIO.HIGH)
    GPIO.output(20, GPIO.HIGH)
    GPIO.output(21, GPIO.HIGH)
    
    red_pwm()
    
    time.sleep(1)


def wedding():
      
    pygame.init()
    pygame.mixer.music.load("wedding.mp3")
    pygame.mixer.music.play()
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    time.sleep(0.5)
    
    fastup()
    time.sleep(1)
    fastup()
    time.sleep(1)
    GPIO.output(7, GPIO.LOW)
    fastup()
    time.sleep(0.2)
    GPIO.output(10, GPIO.LOW)
    fastup()
    time.sleep(0.2)
    GPIO.output(4, GPIO.LOW)
    fastup()
    time.sleep(0.2)
    GPIO.output(23, GPIO.LOW)
    fastup()
    time.sleep(0.2)
    fastup()
    alledgeon()
    time.sleep(1)
    wave()
    time.sleep(0.3)
    
    GPIO.output(5, True)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    alledgeon()
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.4)
      
    midmove()
    midmove()
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.3)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    side1()
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side2()
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side3()
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side4()
    time.sleep(0.2)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side5()
    time.sleep(0.2)
    
    
    alledgeon()
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW)  
    time.sleep(0.5)
    
    
    alledgeoff()
    time.sleep(1)
    
    GPIO.output(5, False)
    wave()
    time.sleep(0.3)
    
    GPIO.output(5, True)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    alledgeon()
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.4)
    
    midmove()
    midmove()
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.3)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    time.sleep(0.5)
    
    fpoint()
    time.sleep(0.5)
    ##again
    
    fastup()
    time.sleep(0.2)
    fastdown()
    
    
    fastup()
    time.sleep(0.2)
    fastdown()
    
    
    GPIO.output(7, GPIO.LOW)
    fastup()
    time.sleep(0.2)
    GPIO.output(10, GPIO.LOW)
    fastup()
    time.sleep(0.2)
    GPIO.output(4, GPIO.LOW)
    fastup()
    time.sleep(0.2)
    GPIO.output(23, GPIO.LOW)
    fastup()
    time.sleep(0.2)
    fastup()
    alledgeon()
    time.sleep(1)
    wave()
    time.sleep(0.3)
    
    GPIO.output(5, True)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    alledgeon()
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.4)
      
    midmove()
    midmove()
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.3)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    side1()
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side2()
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side3()
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side4()
    time.sleep(0.2)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side5()
    time.sleep(0.2)
    
    
    alledgeon()
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW)  
    time.sleep(0.5)
    
    
    alledgeoff()
    time.sleep(1)
    
    GPIO.output(5, False)
    wave()
    time.sleep(0.3)
    
    GPIO.output(5, True)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    alledgeon()
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.4)
    
    midmove()
    midmove()
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.3)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    time.sleep(0.5)
    
    fpoint()
    time.sleep(0.5)
    
    ##heart start
    
    side3()
    fastup()
    time.sleep(1)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    side24()
    time.sleep(1)
    ##side2,4
    
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    side15()
    time.sleep(0.5)
    ##side1,5
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    side24()
    time.sleep(0.5)
    
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side3()
    time.sleep(0.5)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    side24()
    time.sleep(1)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    side15()
    time.sleep(1)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    side24()
    time.sleep(0.5)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side3()
    time.sleep(0.5)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    side24()
    time.sleep(0.5)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    side15()
    time.sleep(0.5)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    side24()
    time.sleep(0.5)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side3()
    time.sleep(1)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    side24()
    time.sleep(0.5)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    side15()
    time.sleep(1)
    
    
    #fast
    manyslowheart()
    manyfastheart()
    
    #again 1
    side2()
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.5)
    
    side3()
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.5)
    
    side4()
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.5)
    
    alledgeon()
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW)  
    time.sleep(1.5)
    
    GPIO.output(5, False)
    wave()
    time.sleep(0.3)
    
    GPIO.output(5, True)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    alledgeon()
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.4)
    
    midmove()
    midmove()
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.3)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    time.sleep(0.5)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    side1()
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side2()
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side3()
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side4()
    time.sleep(0.2)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    side5()
    time.sleep(0.2)
    
    
    alledgeon()
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW)  
    time.sleep(1)

    
    GPIO.output(5, False)
    wave()
    time.sleep(0.3)
    
    GPIO.output(5, True)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    alledgeon()
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, False)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, False)
    
    time.sleep(0.4)
    
    GPIO.output(5, True)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    
    time.sleep(0.4)
    
    midmove()
    midmove()
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.3)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    time.sleep(0.5)
    
    GPIO.output(5, True)
    red_pwm()
    time.sleep(0.5)
    


def carroll():
    pygame.init()
    pygame.mixer.music.load("carroll.mp3")
    pygame.mixer.music.play()
    
    alloff()
    time.sleep(0.5)
    
    alledgeoff()
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW) 
    fastup()
    
    time.sleep(0.1)
    
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, True)
    time.sleep(0.2)
    
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.2)
    
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.2)
    
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, True)
    time.sleep(0.2)
    
    fastup()
    GPIO.output(5, True)
    
    time.sleep(0.1)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    fpoint()
    time.sleep(0.2)
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    
    
    fastup()
    GPIO.output(5, True)
    
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    #snow1
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    
    #snow2
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    #snow3
    
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.3)
    
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    square()
    time.sleep(0.5)
    center()
    time.sleep(0.5)
    
    #swing in1

    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    square()
    time.sleep(0.2)

    
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    
    side5()
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    side1()
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    alledgeoff()
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW) 
    fastup()
    time.sleep(0.3)
    
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    
    
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    edgemove()
    
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    edgemove2()
    
    #again
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    #snow1
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    
    #snow2
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    #snow3
    
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.3)
    
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    square()
    time.sleep(0.5)
    center()
    time.sleep(0.5)
    
    #swing in1

    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    square()
    time.sleep(0.2)

    
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    
    side5()
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    side1()
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    alledgeoff()
    GPIO.output(16, GPIO.LOW)
    GPIO.output(20, GPIO.LOW)
    GPIO.output(21, GPIO.LOW) 
    fastup()
    time.sleep(0.3)
    
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    
    
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    edgemove()
    
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    edgemove()
    
    #again
    center()
    time.sleep(0.5)
    square()
    time.sleep(0.5)
    allon()
    alledgeon()
    time.sleep(0.5)
    
    center()
    time.sleep(0.5)
    square()
    time.sleep(0.5)
    allon()
    alledgeon()
    time.sleep(0.5)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    time.sleep(0.2)
    
    GPIO.output(26, True)
    wave()
    time.sleep(0.5)
    
    center()
    time.sleep(0.5)
    square()
    time.sleep(0.5)
    allon()
    alledgeon()
    time.sleep(0.5)
    
    center()
    time.sleep(0.5)
    square()
    time.sleep(0.5)
    allon()
    alledgeon()
    time.sleep(0.5)
    
    midmove()
    
    center()
    time.sleep(0.5)
    GPIO.output(13, False)
    time.sleep(0.5)
    center()
    time.sleep(0.5)
    GPIO.output(13, False)
    time.sleep(0.5)
    center()
    time.sleep(0.5)
    GPIO.output(13, False)
    time.sleep(0.5)
    center()
    time.sleep(0.3)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    #snow1
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    
    #snow2
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    #snow3
    
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.3)
    
    side5()
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    side1()
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    side3()
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    GPIO.output(26, True)
    GPIO.output(19, True)
    GPIO.output(13, True)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    side24()
    time.sleep(0.4)
    
    side15()
    time.sleep(0.4)
    
    allon()
    alledgeon()
    time.sleep(0.5)
    
    GPIO.output(5, False)
    GPIO.output(6, True)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, True)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, True)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.4)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, False)
    time.sleep(0.2)
    
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, True)
    time.sleep(0.2)
    
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    GPIO.output(5, False)
    GPIO.output(6, False)
    GPIO.output(13, False)
    GPIO.output(19, False)
    GPIO.output(26, True)
    time.sleep(0.2)
    
    square()
    time.sleep(0.5)
    
    alloff()
    time.sleep(0.5)
    
    square()
    time.sleep(0.5)
    
    for i in range(1, 10):
        cross()
        
    for i in range(1, 110):
        randled()
    
    center()
    time.sleep(0.4)
    
    side24()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.4)
    
    side15()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, True)
    time.sleep(0.4)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    #snow1
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    
    #snow2
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    #snow3
    
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.3)
    
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.3)
    
    square()
    time.sleep(0.5)
    center()
    time.sleep(0.5)
    
    #swing in1

    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    oddnumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(0.2)
    
    square()
    time.sleep(0.2)

    
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    GPIO.output(5, False)
    time.sleep(0.2)
    GPIO.output(5, True)
    fpoint()
    time.sleep(0.2)
    
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    edgemove()
    
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    edgemove()
    
    #again
    center()
    time.sleep(0.5)
    square()
    time.sleep(0.5)
    allon()
    alledgeon()
    time.sleep(0.5)
    
    for i in range(1, 8):
        cross()
        
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, True)
    GPIO.output(5, False)
    time.sleep(1)
    
    evennumber()
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, True)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(1)
    
    oddnumber()
    GPIO.output(26, False)
    GPIO.output(19, True)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    time.sleep(1)
    
    evennumber()
    GPIO.output(26, True)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    
    bottom_pwm()
    

while(1):
    fpoint()
    z = int(input("\n\n press the button (1~3) \n 1:birthday song, 2:wedding song, 3:carroll  "))

    
    if z==1:
        z == birthday()
        
    if z==2:
        z == wedding()
        
    if z==3:
        z == carroll()
        
    if z==4:
        z == test()
  
